tunnel: <TUNNEL_ID>
credentials-file: C:/Users/<WORK_PC_USER>/.cloudflared/<TUNNEL_ID>.json

ingress:
  - hostname: all4.collenlabs.uk
    service: https://127.0.0.1:3443
    originRequest:
      noTLSVerify: true
  - service: http_status:404
